"""
Self-refinement strategy.

Generate → Review → Suggestions → Regenerate cycle.
The same agent reviews and refines its own output.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from src.refinement.base import BaseRefinementStrategy

if TYPE_CHECKING:
    from src.agents.base_agent import BaseAgent
    from src.orchestration.artifacts import Artifact
    from src.orchestration.context import SharedContext
    from src.orchestration.orchestrator import Orchestrator

logger = logging.getLogger(__name__)


class SelfRefinement(BaseRefinementStrategy):
    """
    Self-refinement: an agent reviews and improves its own output.

    Cycle:
    1. Generate initial artifact.
    2. Agent reviews its own output.
    3. Agent regenerates with review feedback.
    4. Repeat up to N iterations.
    """

    strategy_name = "self_refinement"

    def refine(
        self,
        agent: BaseAgent,
        context: SharedContext,
        orchestrator: Orchestrator,
    ) -> Artifact:
        """
        Execute self-refinement loop.

        Args:
            agent: The agent performing self-refinement.
            context: The shared context.
            orchestrator: The orchestrator.

        Returns:
            The final refined artifact.
        """
        # Step 1: Initial generation
        artifact = orchestrator.execute_agent(agent, context)
        logger.info(
            "Self-refinement: initial artifact generated by '%s'", agent.name
        )

        # Steps 2-N: Review and regenerate
        for iteration in range(self.iterations):
            logger.info(
                "Self-refinement iteration %d/%d for '%s'",
                iteration + 1,
                self.iterations,
                agent.name,
            )

            # Add current artifact content as review context
            context.reviews.append(
                f"Iteration {iteration + 1}: Review your previous output "
                f"and improve it. Previous output:\n{artifact.content}"
            )

            # Regenerate
            artifact = orchestrator.execute_agent(
                agent, context, previous_agent=f"{agent.name}_review"
            )

        logger.info(
            "Self-refinement completed for '%s' after %d iterations",
            agent.name,
            self.iterations,
        )

        return artifact
